### PR TITLE
[Feature] Logged-in only.

### PR DESCRIPTION
**Pull request by Hackmastr**
Add the ability to make the dashboard loggin only,
Login with Steam.

### CODE REVIEW

**Review by theChaosCoder — COMMENTED** [review]
Very nice!

- The function MustBeLoggedIn() doesn't seem to be used?
- It would be nice if instead of redirect to steam-login directly, a simple page with a steam-login button and some text ("you need to login / only admins allowed etc.") could be added. And a logout redirects again to the login page.

**Comment by Hackmastr** [comment]
Refactor folders, remove dead code (Auth-only).
Replace font-awesome local loading to CDN.
Add login page.

**Comment by theChaosCoder** [comment]
Now we have 2 warnings left ;-) 
`Undefined variable: force_recache` 
See here: https://github.com/Hackmastr/player_analytics/blob/545928b131ece7fbdc152d0413c96944118b6cc6/login.php#L13

I think you should just remove the force_recache var here. You can find it in index.php
`... bootstrap.min.css<?php echo $force_recache ?> ..`

**Comment by Hackmastr** [comment]
Ah right! 'Cause I'm not loading app.php. 
Will push an update in few seconds.

**Pull request merged**
